### PR TITLE
adds more conveniences (lines, numbers)

### PR DESCRIPTION
**Pull request by c17r**
Adds more special functions per #25

### CODE REVIEW

**Comment by wimglenn** [comment]
@c17r  CI says you have a syntax error, but I'm not seeing it... 🤔

**Comment by c17r** [comment]
@wimglenn no worries, I'll take a look

**Comment by c17r** [comment]
That was fun. As I fixed this PR I somehow managed to suck in a commit from my other PR. 🤣

**Comment by wimglenn** [comment]
@c17r  Tests for new features?

**Comment by c17r** [comment]
@wimglenn A couple of unrelated tests were breaking when run under Windows 10 PowerShell. With those fixed, tests added in for `lines` and `numbers`

**Comment by wimglenn** [comment]
LGTM, I want to handle the transforms in a separate module and keep the Aocd class itself simpler, but I'll address that in a follow-up commit.

**Pull request merged**
