### PR TITLE
Improved example data heuristic

### PR DESCRIPTION
**Pull request by rnbwdsh**
See #99

### CODE REVIEW

**Comment by wimglenn** [comment]
@rnbwdsh  Could you adapt this idea for v2.0.0 ?

**Comment by rnbwdsh** [comment]
I'll look into it, because I'm honestly not 100% happy with the hardcoded-location approach of aoce (let's hope eric doesn't change too much in the src :D ), but I'm super glad we have ground truth data now.

Just to be sure: Did you manually verify the... 400 levels? :D So this really is THE ground truth?

And I'm burning to see how well this basic heuristic does compared to the very naive baseline approach.

However I'll probably only get to it in the next week or so because I already totally forgot everything about my code.

**Comment by wimglenn** [comment]
Yeah, I manually verified them. It was a tonne of work. But I'm confident about the results, and when I run my solver against the example datas (using `aoc --example`) it produces the example answers.

I've never seen the prose change from the initial html in a way that would invalidate locators, but it's not out of the realm of possibility.

**Comment by rnbwdsh** [comment]
That is INSANE! This would make such a great benchmark/dataset for NLP / LLMs and a great meta-challenge for the aocd-summer-hole.

I also looked into the aoce and the whole doc of the aocd-example-parser, and I'm really impressed. Good doc. Easy code.

I was so impressed, I even ported my basic heuristic to https://github.com/rnbwdsh/aocd-example-parser-heuristic, and I'll probably look into some improved heuristics. So far your default-one fares better, I think it's not 100% working yet.

**Comment by wimglenn** [comment]
Thanks for the kind words. Regardless of the performance, it's cool to see how quick/easy it was for someone (other than myself) to publish a working plugin.

**Pull request closed without merging**
